### PR TITLE
DEVENGAGE-615 Update gc-cli commands to beta 11.0.0

### PR DESCRIPTION
**Pull request by PrinceMerluza**
Update gc-cli commands to beta 11.0.0

### CODE REVIEW

**Comment by PrinceMerluza** [comment]
By the way I noticed that `routing queues members` use the `get` verb for getting the members of the queue. Other commands use the verb `list` instead for paginated results. 

Anyway, not sure if that was intentional but I just noticed while going through the quick-hits.

**Comment by ronanwatkins** [comment]
> By the way I noticed that `routing queues members` use the `get` verb for getting the members of the queue. Other commands use the verb `list` instead for paginated results.
> 
> Anyway, not sure if that was intentional but I just noticed while going through the quick-hits.

Oh yeah I missed that one. I've updated it in the new CLI PR. You can go ahead and rename references to `routing queues members get` to `routing queues members list`

**Review by ronanwatkins — APPROVED** [review]

**Comment by PrinceMerluza** [comment]
> > By the way I noticed that `routing queues members` use the `get` verb for getting the members of the queue. Other commands use the verb `list` instead for paginated results.
> > Anyway, not sure if that was intentional but I just noticed while going through the quick-hits.
> 
> Oh yeah I missed that one. I've updated it in the new CLI PR. You can go ahead and rename references to `routing queues members get` to `routing queues members list`

Cool. Thanks for the update Ronan. I pushed the changes to the PR.

**Comment by carnellj** [comment]
Nice Prince.  @ronanwatkins will merge this once we know we are ready for release review.

**Pull request merged**
